### PR TITLE
Add custom context menu sample.

### PR DESCRIPTION
**Pull request by MayaKirova**

### CODE REVIEW

**Comment by MayaKirova** [comment]
Unfortunately `If the selected cell is within a multi-cell selection range, copy all the selected data.` cannot be implemented since the GetSelectedRanges API does not work in blazor.
https://infragistics.visualstudio.com/NetAdvantage/_workitems/edit/24800

**Comment by mddragnev** [comment]
Screenshot 2023-06-13 at 15 14 53
@MayaKirova The context menu opens on weird position. Not evne close to the cell that is right cliked

**Comment by MayaKirova** [comment]
@mddragnev 
Is there something specific that needs to happen to reproduce this. For me it opens exactly on the right clicked position:
menu

**Comment by mddragnev** [comment]
@MayaKirova Seems to only reproduce in the samples browser.

**Comment by mddragnev** [comment]
As we discussed this is something related to the navigation drawer in the samples browser. It does not reproduce within the iframe that the docfx uses. We can skip finding a workaround for it.

**Review by mddragnev — APPROVED** [review]

**Review by HUSSAR-mtrela — APPROVED** [review]

**Pull request merged**
