### PR TITLE
Update clipboard operations sample.

### PR DESCRIPTION
**Pull request by MayaKirova**
Update UI elements since the property editor ones do not work correctly.

### CODE REVIEW

**Review by HUSSAR-mtrela — CHANGES_REQUESTED** [review]
this sample is exported from xplat samples
https://github.com/IgniteUI/igniteui-xplat-examples/blob/vnext/samples/grids/grid/clipboard-operations.json
but I do not see a PR with your changes in igniteui-xplat-examples repo. Did you forget to create the PR or are you converting this xplat samples to platform specific sample?

**Comment by MayaKirova** [comment]
@HUSSAR-mtrela I disabled in this PR: https://github.com/IgniteUI/igniteui-xplat-examples/pull/199
With the intention of adding platform specific samples for WC and Blazor.

By the way, could you not merge PRs since @dkamburov would also like to review and test it before merging.

**Comment by HUSSAR-mtrela** [comment]
@MayaKirova thanks for explaining

**Comment by mddragnev** [comment]
@MayaKirova The sample throws error
Screenshot 2023-05-16 at 16 26 44

**Review by mddragnev — APPROVED** [review]

**Review by HUSSAR-mtrela — CHANGES_REQUESTED** [review]
still waiting for a complete PR in xplat-examples repo that should remove xplat samples that are being converted to platform specific samples. This way, we do not override platform specific samples by disabled xplat samples.

**Review by HUSSAR-mtrela — APPROVED** [review]

**Comment by HUSSAR-mtrela** [comment]
waiting for @mddragnev review

**Comment by mddragnev** [comment]
@dkamburov Can we please merge this cus the topic and the sampels are missing for blazor

**Pull request merged**
